// AUTO-GENERATED by scripts/generate-protocol.mjs — DO NOT EDIT.
//
// Source schema: schemas/protocol-schema.json
// Vendored from Android-Display-App @ e0b2069a (protocol vc146).
// Regenerate with: yarn generate-protocol

// ----------------------------------------------------------------
// Command
// ----------------------------------------------------------------

export const COMMAND_TYPES = [
	'add_message',
	'add_session',
	'add_time',
	'delete_all_messages',
	'delete_all_sessions',
	'delete_message',
	'delete_program',
	'delete_session',
	'get_program',
	'get_program_list',
	'hide_message',
	'move_message_down',
	'move_message_up',
	'move_session_down',
	'move_session_up',
	'navigate_next_session',
	'navigate_previous_session',
	'pause_session',
	'request_control_center_status',
	'request_messages_status',
	'request_sessions_status',
	'request_settings_status',
	'request_status',
	'request_view_status',
	'reset_current_session',
	'reset_program_elapsed_timer',
	'send_program',
	'set_blackout',
	'set_brightness',
	'set_flash',
	'set_glow',
	'set_is_time_up_display',
	'show_idle',
	'show_message',
	'show_session',
	'start_session',
	'subtract_time',
	'toggle_flash',
	'toggle_glow',
	'toggle_is_time_up_display',
	'update_message',
	'update_session',
] as const

export type CommandType = (typeof COMMAND_TYPES)[number]

const COMMAND_TYPE_SET: ReadonlySet<string> = new Set(COMMAND_TYPES)

export interface CommandJsonProgram {
	settings: CommandJsonProgramSettings
	sessions: CommandJsonSession[]
	user_id?: string | null
	program_id: string
	program_name: string
	messages?: CommandJsonMessage[]
	version: string
}

export interface CommandJsonMessage {
	is_flashing?: boolean
	is_showing?: boolean
	id?: string
	version?: string
	content: string
}

export interface CommandJsonProgramSettings {
	flash_start_time_seconds?: number
	flash_length_seconds?: number
}

export interface CommandJsonSession {
	duration_seconds?: number | null
	mode?: string
	started_at_timestamp?: number | null
	notes?: string
	offset?: number | null
	flash_start_time_seconds?: number
	flash_length_seconds?: number
	name: string
	id?: string
	presenter_name?: string | null
	version?: string
}

export interface CommandPayloads {
	add_message: {
		content: string
	}
	add_session: {
		mode?: string
		seconds?: number | null
		notes?: string | null
		offset?: number | null
		flash_start_time_seconds?: number | null
		flash_length_seconds?: number | null
		name?: string | null
		session_id?: string | null
		presenter_name?: string | null
	}
	add_time: {
		seconds?: number | null
		ms?: number | null
	}
	delete_all_messages: {}
	delete_all_sessions: {}
	delete_message: {
		message_id: string
	}
	delete_program: {
		program_id: string
	}
	delete_session: {
		session_id: string
	}
	get_program: {}
	get_program_list: {}
	hide_message: {}
	move_message_down: {
		message_id: string
	}
	move_message_up: {
		message_id: string
	}
	move_session_down: {
		session_id: string
	}
	move_session_up: {
		session_id: string
	}
	navigate_next_session: {}
	navigate_previous_session: {}
	pause_session: {}
	request_control_center_status: {}
	request_messages_status: {}
	request_sessions_status: {}
	request_settings_status: {}
	request_status: {
		detailed?: boolean
	}
	request_view_status: {}
	reset_current_session: {}
	reset_program_elapsed_timer: {}
	send_program: {
		program: CommandJsonProgram
	}
	set_blackout: {
		action: string
	}
	set_brightness: {
		brightness: number
	}
	set_flash: {
		action: string
	}
	set_glow: {
		enabled: boolean
	}
	set_is_time_up_display: {
		enabled: boolean
	}
	show_idle: {}
	show_message: {
		message_id?: string | null
		text?: string | null
		flash?: boolean
	}
	show_session: {
		session_id: string
	}
	start_session: {
		session_id?: string | null
	}
	subtract_time: {
		seconds?: number | null
		ms?: number | null
	}
	toggle_flash: {}
	toggle_glow: {}
	toggle_is_time_up_display: {}
	update_message: {
		message_id: string
		content: string
	}
	update_session: {
		mode?: string | null
		seconds?: number | null
		notes?: string | null
		offset?: number | null
		flash_start_time_seconds?: number | null
		flash_length_seconds?: number | null
		name?: string | null
		session_id: string
		presenter_name?: string | null
	}
}

export type Command = {
	[K in CommandType]: { type: K } & CommandPayloads[K] & { request_id: string }
}[CommandType]

// ----------------------------------------------------------------
// Response
// ----------------------------------------------------------------

export const RESPONSE_TYPES = [
	'ack_response',
	'control_center_status_response',
	'error_response',
	'messages_status_response',
	'program_list_response',
	'program_response',
	'sessions_status_response',
	'settings_status_response',
	'status_response',
	'view_status_response',
] as const

export type ResponseType = (typeof RESPONSE_TYPES)[number]

const RESPONSE_TYPE_SET: ReadonlySet<string> = new Set(RESPONSE_TYPES)

export interface ResponseJsonMessagesStatus {
	message_list: ResponseJsonMessageSummary[]
	is_flashing: boolean
}

export interface ResponseJsonMessageSummary {
	is_showing: boolean
	id: string
	text: string
}

export interface ResponseJsonSettingsStatus {
	brightness: number
	is_time_up_display: boolean
	default_flash_length: number
	default_flash_start_time: number
	view_only_code?: string | null
	screen_version: string
}

export interface ResponseJsonSessionsStatus {
	session_list: ResponseJsonSessionSummary[]
}

export interface ResponseJsonSessionSummary {
	notes: string
	offset?: number | null
	index: number
	presenter_name?: string | null
	version: string
	duration?: number | null
	mode: string
	started_at_timestamp?: number | null
	flash_start_time_seconds: number
	flash_length_seconds: number
	name: string
	id: string
	is_current: boolean
}

export interface ResponseJsonControlCenterStatus {
	flash_start_time: number
	is_next_session: boolean
	current_presenter_name: string
	current_session_name: string
	current_session_id: string
	current_session_index: number
	is_blackout: boolean
	program_time: number
	is_glowing: boolean
	timer_run_state: string
	is_time_up_flashing: boolean
	timer: number
	is_previous_session: boolean
	elapsed_time: number
	flash_length: number
	program_elapsed_time: number
}

export interface ResponseJsonViewStatus {
	is_time_up_flashing: boolean
	session_name: string
	message_text: string
	is_flashing: boolean
	elapsed_time: number
	session_id: string
	message_id?: string | null
	presenter_name: string
	progress_bar: number
	is_glowing: boolean
	program_elapsed_time: number
}

export interface ResponseJsonProgram {
	settings: ResponseJsonProgramSettings
	sessions: ResponseJsonSession[]
	user_id?: string | null
	program_id: string
	program_name: string
	messages?: ResponseJsonMessage[]
	version: string
}

export interface ResponseJsonMessage {
	is_flashing?: boolean
	is_showing?: boolean
	id?: string
	version?: string
	content: string
}

export interface ResponseJsonProgramSettings {
	flash_start_time_seconds?: number
	flash_length_seconds?: number
}

export interface ResponseJsonSession {
	duration_seconds?: number | null
	mode?: string
	started_at_timestamp?: number | null
	notes?: string
	offset?: number | null
	flash_start_time_seconds?: number
	flash_length_seconds?: number
	name: string
	id?: string
	presenter_name?: string | null
	version?: string
}

export interface ResponseJsonProgramSummary {
	program_id: string
	name: string
}

export interface ResponsePayloads {
	ack_response: {
		message: string
		entity_id?: string | null
	}
	control_center_status_response: {
		control_center: ResponseJsonControlCenterStatus
	}
	error_response: {
		code: string
		message: string
	}
	messages_status_response: {
		messages: ResponseJsonMessagesStatus
	}
	program_list_response: {
		program_list: ResponseJsonProgramSummary[]
	}
	program_response: {
		has_program: boolean
		program?: ResponseJsonProgram
	}
	sessions_status_response: {
		sessions: ResponseJsonSessionsStatus
	}
	settings_status_response: {
		settings: ResponseJsonSettingsStatus
	}
	status_response: {
		settings?: ResponseJsonSettingsStatus
		view?: ResponseJsonViewStatus
		sessions?: ResponseJsonSessionsStatus
		messages?: ResponseJsonMessagesStatus
		control_center?: ResponseJsonControlCenterStatus
	}
	view_status_response: {
		view: ResponseJsonViewStatus
	}
}

export type Response = {
	[K in ResponseType]: { type: K } & ResponsePayloads[K] & { request_id?: string | null }
}[ResponseType]

// ----------------------------------------------------------------
// Event
// ----------------------------------------------------------------

export const EVENT_TYPES = [
	'control_center_status_event',
	'hello_event',
	'messages_status_event',
	'program_changed_event',
	'sessions_status_event',
	'settings_status_event',
	'view_status_event',
] as const

export type EventType = (typeof EVENT_TYPES)[number]

const EVENT_TYPE_SET: ReadonlySet<string> = new Set(EVENT_TYPES)

export interface EventJsonMessagesStatus {
	message_list: EventJsonMessageSummary[]
	is_flashing: boolean
}

export interface EventJsonMessageSummary {
	is_showing: boolean
	id: string
	text: string
}

export interface EventJsonSettingsStatus {
	brightness: number
	is_time_up_display: boolean
	default_flash_length: number
	default_flash_start_time: number
	view_only_code?: string | null
	screen_version: string
}

export interface EventJsonSessionsStatus {
	session_list: EventJsonSessionSummary[]
}

export interface EventJsonSessionSummary {
	notes: string
	offset?: number | null
	index: number
	presenter_name?: string | null
	version: string
	duration?: number | null
	mode: string
	started_at_timestamp?: number | null
	flash_start_time_seconds: number
	flash_length_seconds: number
	name: string
	id: string
	is_current: boolean
}

export interface EventJsonControlCenterStatus {
	flash_start_time: number
	is_next_session: boolean
	current_presenter_name: string
	current_session_name: string
	current_session_id: string
	current_session_index: number
	is_blackout: boolean
	program_time: number
	is_glowing: boolean
	timer_run_state: string
	is_time_up_flashing: boolean
	timer: number
	is_previous_session: boolean
	elapsed_time: number
	flash_length: number
	program_elapsed_time: number
}

export interface EventJsonViewStatus {
	is_time_up_flashing: boolean
	session_name: string
	message_text: string
	is_flashing: boolean
	elapsed_time: number
	session_id: string
	message_id?: string | null
	presenter_name: string
	progress_bar: number
	is_glowing: boolean
	program_elapsed_time: number
}

export interface EventJsonProgram {
	settings: EventJsonProgramSettings
	sessions: EventJsonSession[]
	user_id?: string | null
	program_id: string
	program_name: string
	messages?: EventJsonMessage[]
	version: string
}

export interface EventJsonMessage {
	is_flashing?: boolean
	is_showing?: boolean
	id?: string
	version?: string
	content: string
}

export interface EventJsonProgramSettings {
	flash_start_time_seconds?: number
	flash_length_seconds?: number
}

export interface EventJsonSession {
	duration_seconds?: number | null
	mode?: string
	started_at_timestamp?: number | null
	notes?: string
	offset?: number | null
	flash_start_time_seconds?: number
	flash_length_seconds?: number
	name: string
	id?: string
	presenter_name?: string | null
	version?: string
}

export interface EventPayloads {
	control_center_status_event: {
		control_center: EventJsonControlCenterStatus
	}
	hello_event: {
		version_name: string
		screen_name: string
		version_code: number
		screen_id: string
	}
	messages_status_event: {
		messages: EventJsonMessagesStatus
	}
	program_changed_event: {
		has_program: boolean
		program?: EventJsonProgram
	}
	sessions_status_event: {
		sessions: EventJsonSessionsStatus
	}
	settings_status_event: {
		settings: EventJsonSettingsStatus
	}
	view_status_event: {
		view: EventJsonViewStatus
	}
}

export type Event = {
	[K in EventType]: { type: K } & EventPayloads[K]
}[EventType]

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

/** Fresh correlation id for every command. */
export function newRequestId(): string {
	return globalThis.crypto.randomUUID()
}

/**
 * Builds a command envelope with its `type` discriminator and a fresh
 * `request_id` (overridable for tests).
 */
export function buildCommand<K extends CommandType>(
	type: K,
	payload: CommandPayloads[K],
	requestId: string = newRequestId(),
): { type: K; request_id: string } & CommandPayloads[K] {
	return { request_id: requestId, ...payload, type } as { type: K; request_id: string } & CommandPayloads[K]
}

/** Parses one inbound WS frame into a typed Response or Event, or null. */
export function parseInbound(text: string): Response | Event | null {
	let value: unknown
	try {
		value = JSON.parse(text)
	} catch {
		return null
	}
	if (typeof value !== 'object' || value === null) return null
	const type = (value as { type?: unknown }).type
	if (typeof type !== 'string') return null
	if (RESPONSE_TYPE_SET.has(type)) return value as Response
	if (EVENT_TYPE_SET.has(type)) return value as Event
	return null
}

/** Narrows a parsed message to a Response. */
export function isResponse(msg: Response | Event): msg is Response {
	return RESPONSE_TYPE_SET.has(msg.type)
}

/** Narrows a parsed message to an Event. */
export function isEvent(msg: Response | Event): msg is Event {
	return EVENT_TYPE_SET.has(msg.type)
}
