#!/usr/bin/env node
/**
 * Generates src/generated-icons.ts from PNG files in icons_232/
 *
 * Run this before tsc to embed icon data into the module.
 * To add or update icons, just place PNG files in icons_232/ and rebuild.
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const iconsDir = join(__dirname, '..', 'icons_232')
const outFile = join(__dirname, '..', 'src', 'generated-icons.ts')

let files
try {
	files = readdirSync(iconsDir).filter((f) => f.endsWith('.png'))
} catch {
	console.error('icons_232/ directory not found — skipping icon generation')
	writeFileSync(outFile, '// No icons found — presets will use text-only styles\n')
	process.exit(0)
}

const lines = ['// Auto-generated by scripts/generate-icons.mjs', '// Do not edit directly — update icons in icons_232/ and rebuild', '']

for (const file of files.sort()) {
	const key = file.replace('.png', '').replace(/[^a-zA-Z0-9_]/g, '_')
	const data = readFileSync(join(iconsDir, file))
	const b64 = data.toString('base64')
	lines.push(`export const icon_${key}: string = '${b64}'`)
}

lines.push('')
writeFileSync(outFile, lines.join('\n'))
console.log(`Generated ${outFile} (${files.length} icons)`)
